### ISSUE TITLE
SSH admin key creation fails

### ISSUE THREAD

**Issue by psmallwood-ot** [csmart/ansible-role-swift#1]
TASK [csmart.swift : Generate SSH admin key]
fatal: [swift-admin]: FAILED! => {"changed": false, "msg": "The directory /root/.ssh does not exist or the file is not a directory", "name": "/root/.ssh"}

Generally, a truly fresh install won't have this directory, so the ansible-role-swift should add a task to create that directory.

Manually creating the directory allowed the task to complete.

**Comment by csmart** [comment]
Hi @psmallwood-ot, thanks for reporting this. I don't seem to hit this issue in my tests, perhaps my VMs already have that directory. I'll do some more tests and see, although I'll probably just add a step to make sure that directory exists with the right permissions to make it work regardless.

Out of curiosity, can you tell me what version of Ansible you're using and what host OS you're executing the playbooks from?

Thanks!
-c

**Comment by psmallwood-ot** [comment]
The launch machine is running CentOS Linux 7.9.2009 (currently fully up to date, not stream), and Ansible is 2.9.25 with core at 2.11.4.

**Comment by csmart** [comment]
Great, thanks.

**Comment by csmart** [comment]
Yes, confirmed that my virtual machines already have that `/root/.ssh` directory, so I will add a fix for that shortly.
